export const PAGINATION = {
  DEFAULT_PAGE: 1,
  DEFAULT_PER_PAGE: 20,
  MAX_PER_PAGE: 100,
  LESSON_PER_PAGE: 12,
} as const;

export const VALIDATION = {
  PASSWORD_MIN_LENGTH: 8,
  FULL_NAME_MIN: 2,
  FULL_NAME_MAX: 100,
  TITLE_MIN: 5,
  TITLE_MAX: 200,
  LESSON_THEORY_MIN: 10,
  LESSON_ESTIMATED_MIN: 5,
  LESSON_ESTIMATED_MAX: 180,
  GRADE_MIN: 1,
  GRADE_MAX: 12,
} as const;

export const VN_PHONE_REGEX = /^(\+84|0)[0-9]{9}$/;
